import type {Metadata} from "next";
import localFont from "next/font/local";
import {
    ClerkProvider,
} from '@clerk/nextjs'

import "./globals.css";
import {QueryProviders} from "@/providers/query-provider";
import {SheetProvider} from "@/providers/sheet-provider";
import {Toaster} from "@/components/ui/sonner";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Finance Management",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <QueryProviders>
                    <SheetProvider/>
                    <Toaster/>
                    {children}
                </QueryProviders>
            </body>
            </html>
        </ClerkProvider>
    )
}
